### ISSUE TITLE
index.html will not generate unless prerender: { default: true }

### ISSUE THREAD

**Issue by ghost** [michmich112/sveltekit-adapter-chrome-extension#12]
Please correct the documentation to show a working config for Svelte's current stock configuration
```
import adapter from 'sveltekit-adapter-chrome-extension';

export default {
  kit: {
    adapter: adapter({
      // default options are shown
      pages: "build",
      assets: "build",
      fallback: null,
      precompress: false,
    }),
    appDir: "app",
    prerender: { default: true },
  },
};
```

**Comment by prasunkar** [comment]
I'm having this issue as well. `config.kit.prerender.default` has been removed as of now, and no `index.html` is being generated upon build.
<img width="1303" alt="Screenshot 2022-09-01 at 12 15 38 AM" src="https://user-images.githubusercontent.com/32245056/187830380-485fe6bd-3067-44e7-95b0-579755860f64.png">

**Comment by michmich112** [comment]
Hi @prasunkar can you tell me what version of Svelte kit youy are using so we can replicate the issue?

**Comment by prasunkar** [comment]
This was using the latest version of SvelteKit (`@sveltejs/kit 1.0.0-next.463`). Steps to reproduce include:

1. Initialize a new Svelte app (skeleton project with typescript, eslint, and prettier), `pnpm create svelte@latest my-app`
2. Install this package, `pnpm add -D sveltekit-adapter-chrome-extension`
3. Create a manifest in the static folder and copy over the documented configuration into the Svelte config file
4. Start the dev server or try building for production and this error will occur:
<img width="1455" alt="Screenshot 2022-09-02 at 4 09 13 PM" src="https://user-images.githubusercontent.com/32245056/188228797-6b31fc62-51af-41f3-a08d-7568140f4d65.png">

I rolled SvelteKit back to `@sveltejs/kit 1.0.0-next.454` and followed the exact reproduction steps without error and the index.html file appears in the build folder, as it should. This SvelteKit version appears to be fine with the current version of this package.

**Comment by michmich112** [comment]
Cheers @prasunkar 
Created issue #18 for this breaking change
