### ISSUE TITLE
no index.html in build directory

### ISSUE THREAD

**Issue by sebmade** [michmich112/sveltekit-adapter-chrome-extension#25]
just start working with this with the lastest version of sveltekit
npm run build don't generate index.html in the build directory
do I miss something ?

**Comment by wallw-dev** [comment]
You probably want `src/routes/+layout.js` (or `+layout.ts` for typescript projects) with the following:
```javascript
export const ssr = false
```

**Comment by sebmade** [comment]
that's it, thanks
I was thinking the adapter do the work for me ;)

**Comment by wallw-dev** [comment]
I'm working on mine now, this is better:

```javascript
export const prerender = true;
```
and remove the previous line above.
