### ISSUE TITLE
Unable to find the app.html in the build dir

### ISSUE THREAD

**Issue by ziedHamdi** [michmich112/sveltekit-adapter-chrome-extension#27]
Hi,

I'm a react developer seduced by the svelte syntax, so I thought I'd write my next chrome extension with it.

My build directory is missing the html file:
![image](https://user-images.githubusercontent.com/7271508/218303017-7f2d1dcd-e304-40af-a806-9ec60c88487c.png)

I started a new project in a few steps:
**npm init svelte@latest**
![image](https://user-images.githubusercontent.com/7271508/218303064-fb1b4027-33a3-4fcf-b655-9964650b4955.png)

**pnpm i -D sveltekit-adapter-chrome-extension**
**changed the svelte.config.js and added a manifest.json to the static dir**
**pnpm run build**

 
![image](https://user-images.githubusercontent.com/7271508/218303130-5fbc7aa1-45e9-470e-9eb2-24158c2da0b9.png)

Did I miss something in the process? I can't find the html file

Here's my project structure:
![image](https://user-images.githubusercontent.com/7271508/218303723-75371294-b955-4ec9-ba9c-a89aeda4cd00.png)

**Comment by wallw-dev** [comment]
I think you may have missed this note in the readme:

> 🚧 If you are using SvelteKit v1.0.0+, make sure to set your prerender=true for every page reference by your extension so SvelteKit generates the HTML files.

So add a `src/routes/+layout.js` file which looks like this:
```javascript
export const prerender = true;
```

You can see the [Svelte Kit docs for that option here](https://kit.svelte.dev/docs/page-options#prerender) and they also have a note about using it with [Static Site Generation here](https://kit.svelte.dev/docs/adapter-static).

**Comment by ziedHamdi** [comment]
Great! 

Thank you, that worked.
