### ISSUE TITLE
404 /options/index.html (linked from /options) error

### ISSUE THREAD

**Issue by thdoan** [michmich112/sveltekit-adapter-chrome-extension#3]
I have stumbled on a build problem -- whenever you have an internal extensions link, it results in a 404 error on build:

```
> Using sveltekit-adapter-chrome-extension
> 404 /options/index.html (linked from /options)
```

An error is also thrown for the extension:
![image](https://user-images.githubusercontent.com/4110567/155932557-82fd680d-3fd7-4ca9-9d5f-c9177db47fad.png)

A minimal test case is attached:

1. Unzip
2. `npm install`
3. `npm run dev:extension`

[sveltekit-template.zip](https://github.com/michmich112/sveltekit-adapter-chrome-extension/files/8150960/sveltekit-template.zip)

**Comment by michmich112** [comment]
Thank you for finding this bug with the test case!
I'll run it and see what could be the cause!

**Comment by michmich112** [comment]
I think the error comes from the new way that svelte bundles the code and your layout.
![Screen Shot 2022-02-27 at 10 21 19 PM](https://user-images.githubusercontent.com/20456444/155934226-56010af0-7b4b-4d55-aee8-9075511e69d2.png)
as you can see above, the HTML is not bundled into `<directory>/index.html` but rather `<directory>.html` and then links the js with that path. 

try the following in your `__layout.svelte` and it should do the trick ;)

![Screen Shot 2022-02-27 at 10 20 40 PM](https://user-images.githubusercontent.com/20456444/155934147-bacc9646-7ed1-46b2-b4cf-846cb5d05513.png)

Let me know if it does work for you!

**Comment by thdoan** [comment]
I just tried as you suggested and got the same error, but this time I can no longer navigate to the internal pages like `/help.html`:

![image](https://user-images.githubusercontent.com/4110567/155934872-6d833751-c42f-4b3e-8598-8ef0a24e319f.png)

**Comment by michmich112** [comment]
ok i'll elevate this issue. 
I'll probably have an update and fix ready in the next 12h.

**Comment by thdoan** [comment]
Thanks for looking into it! No rush since I'm just exploring SvelteKit + your awesome adapter at the moment. By the way, I also tried other patterns like creating files in `route/options/index.svelte` and `route/help/index.svelte` and got the same error.

**Comment by thdoan** [comment]
Looks like someone experienced a similar issue with static adapter:
https://community.prismic.io/t/404-failure-with-static-adapter-for-sveltekit/5946

Not sure how relevant it is, but I also found this issue:
https://github.com/sveltejs/kit/issues/1329

**Comment by michmich112** [comment]
Probably linked as i based this adapter on the static adapter

**Comment by michmich112** [comment]
@thdoan Made it work.
I've attached the zip file of the working extension. To use run `npm run build`
Problems I found: 
- with the `dev:extension` script, there was a problem when bundling your ts scripts into js scripts. what usually do is that i write them directly in js and put them in the `static` folder (it works and avoids complicated linking but removes the ability to "import" them in you svelte pages. I believe the import functionality does not really matter for content scripts and background scripts/service workers as they cannot communicate through normal means with a MV3 environment).
- There was the linking in the `__layout.svelte` that we had corrected previously but we needed to update the path in the `manifest.json` file as well.
- There was no default action when testing so the extension would not have a visible popup when i would test it. I added an `index.svelte` file as well as an `action` property in your `manifest.json` file.

Let me know if any of this helps!

[sveltekit-template-fixes.zip](https://github.com/michmich112/sveltekit-adapter-chrome-extension/files/8155805/sveltekit-template-fixes.zip)

**Comment by thdoan** [comment]
@michmich112 thanks for the fixes. The build error went away, but now when I go to either popup.html or help.html I get this error:

![image](https://user-images.githubusercontent.com/4110567/156080111-3e4c7f02-4d22-4f54-84c9-1bf799042e23.png)

It's definitely progress though :-).

**Comment by michmich112** [comment]
@thdoan Are there any changes you made? there should not be a file named `
popup.html`.

**Comment by thdoan** [comment]
@michmich112 same error with popup:
![image](https://user-images.githubusercontent.com/4110567/156081538-53a56694-05bc-488f-9422-290fd3433d49.png)

Since the extension I'd like to make doesn't require a popup, I will not be using `action` in manifest.json, which still builds okay after your changes (but throws these JS errors when opening any internal HTML page). I've attached a revised test case below which adds a background script (service worker) and content script. Some other observations:

1. `npm run build` prevents extension from being installed because it doesn't deploy background.js and content.js to `build/js` (hence I had to use `npm run dev:extension`). Would we need to change something in package.json to ensure `npm run build` correctly deploys the background and content scripts for a production build?
2. `npm run package`  results in "lib does not exist" error. This can be removed from your project if it's not used.

[sveltekit-ext-test2.zip](https://github.com/michmich112/sveltekit-adapter-chrome-extension/files/8157860/sveltekit-ext-test2.zip)

**Comment by thdoan** [comment]
Btw, I was trying to figure out how come it was building to `options/index.html` in my original test case (sveltekit-template.zip) but `options.html` in your test case (sveltekit-template-fixes.zip) -- then I finally figured it out: my vite was outdated...

[package-lock.json]
```
      "dependencies": {
        "@sveltejs/vite-plugin-svelte": "^1.0.0-next.32",
        "sade": "^1.7.4",
        "vite": "^2.7.2"
      },
```

After updating vite to v2.8.0, the build issues went away (after updating the HTML file paths), but it introduced this new "Uncaught TypeError: Cannot read properties of null (reading 'parentNode')" error x_x.

**Comment by michmich112** [comment]
@thdoan Thats great! I think then the only think needed to solve it is bump the `sveltekit-adapter-chrome-extension` to v`1.0.1-next.1` (lastest version)

**Comment by thdoan** [comment]
@michmich112 upgrading to v1.0.1-next.1 fixed all issues. Thank you!

**Comment by michmich112** [comment]
![200 (3)](https://user-images.githubusercontent.com/20456444/156277914-98972544-f7f4-4461-a665-23f58ec831ac.gif)

side note: @matyanson created a template and i use it whenever i start new extensions ;) sets up many things out of the box: https://github.com/Matyanson/SvelteKit-browser-extension-template
